//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Game.Logic
{
	public class RowList : List<Row>, IRowList
	{
		#region IRowList implementation
		public void Renumber ()
		{
			Row r = null;
			for (int i = 0; i < this.Count; i++) {
				r = this[i];
				if (r != null) {
					r.SetNumber(i);
				}
			}
		}
		public void AddTop (Row r)
		{
			this.Insert (0, r);
		}
		public void AddBottom (Row r)
		{
			this.Add (r);
		}
		public void RemoveRow (Row r)
		{
			this.Remove (r);
			Renumber ();
		}
		public void RemoveRow (int index)
		{
			throw new NotImplementedException ();
		}
		public Row GetFirstRow ()
		{
			throw new NotImplementedException ();
		}
		public Row GetLastRow ()
		{
			throw new NotImplementedException ();
		}
		public void Trim ()
		{
			for (int i = 0; i < this.Count; i++) {
				if (this[i] == null) {
					this.RemoveAt(i);
				}
			}
		}

		public void Move (int dir)
		{
			Row r = null;
			for (int i = 0; i < this.Count; i++) {
				r = this[i];
				if (r != null) {
					r.Move(dir);
				}
			}
		}

		public void LongMove (float length)
		{
			Row r = null;
			for (int i = 0; i < this.Count; i++) {
				r = this[i];
				if (r != null) {
					r.LongMove(length);
				}
            }
        }

		public void Destroy ()
		{
			Row r = null;
			for (int i = 0; i < this.Count; i++) {
				r = this[i];
				if (r != null) {
					r.Waste();
				}
			}

			this.Clear ();
		}
		#endregion
	}
}

