//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Game.Logic
{
	public class NormalBall : Ball
	{
		public override void Awake ()
		{
			base.Awake ();
			_listener.CollideEvent.AddListener (GetController<NormalBallController>().Collision);
		}

		public void Init (LevelConfig conf)
		{
			mLevelConfig = conf;
		}

		public void SetColor (int n)
		{
			Color c = mLevelConfig.mColors[n];
		}
	}
}

